language: android
jdk: oraclejdk8
android:
  components:
    - tools # Update preinstalled tools from revision 24.0.2 to 24.4.1
    - platform-tools
    - tools # Update tools from revision 24.4.1 to 25.2.5
    - build-tools-25.0.2
    - android-25
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - sys-img-armeabi-v7a-android-25
  licenses:
    - .+
before_install:
  # A workaround to accept the Constraint Layout's licenses
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - rvm install 2.4.0
install:
  - bundle install
script:
  - bundle exec danger
  - ./gradlew test --stacktrace
notifications:
  slack:
    secure: TiiDiGcREuGyrN03ncqC5YgWpP/OJSh/YMbdBkV6k6X8Svz+T1CkaPpCifkHDqOYRrZ99xATb6hLbmTtZ9UJv10aAK2Edoz5bLc+klbOth7b3h/jLS4mUGpHZacJq6IuFJNyfy5eyHICG9LWrRvtI2VGmUONj/PItROVRqP1sWd5YBCt6A7R1NTkx1iJJzfE9TBiXzcGMVd+dajj4MRv7D6D117/MC9MZc2vNuwTdOsr5THyu9ayk3SjA4FzjM8DjB1Sqe/sKRXJO2S/bBIj6F4Popg8J74rFyj/grzqvXRhFUwWvD2yar6tD32XmyVgXx3zWTU76FPqNmrhKZxr6LMHpdFUUvTth7Gd97FT4WWhQ+ijIVZAArkvvridg6YK99YMrmznWbfLXRvqRH+3p5kXh6xdo1oPgIpz/2AWU5th3HgtQDM4tnTvktCSCEphp8zFjcw1vvIUsjtS1kRMvnNfhy1rOfuG+kkblCn4t/MFXnxa3ZtSLGVkiRhOE24wFFKspDPHVXZd2ISf/V1fY2V0Rml1Lojf6OoFickaFzyqOzN3jp1phKNTDha1z3LAJhFhZV6r1yS8cTzxvMitigdJMByJBpmJ0EGQEbAT+m5kNg+C0Z6d3otr4TlW0PHu6iKzD2C1BOPSw8CnaOj51ve+zZYtztJvw3+xfEynPCk=
    on_success: never
    on_failure: always
