fastlane_version "2.37.0"

default_platform :android

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to HockeyApp"
  lane :beta do
    gradle(task: "assembleDebug")
    raise "You must specify a FL_HOCKEY_API_TOKEN environment variable to deploy." if ENV['FL_HOCKEY_API_TOKEN'].nil?
    hockey(
      notes: last_git_commit[:message],
      notify: '0',
    )
    slack(
      default_payloads: [],
      payload: {
        "Git Commit" => last_git_commit[:message],
        'Download'=> lane_context[SharedValues::HOCKEY_DOWNLOAD_LINK],
      },
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end
